const NOTIFICATION_TYPES = Object.freeze([
  'TASK_ASSIGNED',
  'TASK_UPDATED',
  'HELP_REQUEST_CREATED',
  'HELP_REQUEST_UPDATED',
  'HELP_REQUEST_STATUS_CHANGED',
  'SAFETY_CIRCLE_INVITE_RECEIVED',
  'SAFETY_CIRCLE_INVITE_RESPONDED',
  'SAFETY_CIRCLE_STATUS_UPDATED',
  'SAFETY_CIRCLE_UPDATED',
  'ANNOUNCEMENT_PUBLISHED',
  'ANNOUNCEMENT_UPDATED',
  'VOLUNTEER_AVAILABILITY_EXPIRING',
  'VOLUNTEER_AVAILABILITY_PAUSED',
  'SYSTEM',
]);

module.exports = {
  NOTIFICATION_TYPES,
};
