ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_banned BOOLEAN;

ALTER TABLE users
  ALTER COLUMN is_banned SET DEFAULT FALSE;

UPDATE users
SET is_banned = FALSE
WHERE is_banned IS NULL;

ALTER TABLE users
  ALTER COLUMN is_banned SET NOT NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS ban_reason TEXT;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS banned_at TIMESTAMP;
