name: Feature
description: Define a new feature for the project
title: "[FEATURE] "
labels: ["enhancement"]

body:
  - type: input
    id: objective
    attributes:
      label: Primary Objective
      placeholder: e.g., Implement user authentication
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain the reasoning and purpose behind this feature.
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define the boundaries and extent of this feature.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Feature Details
      description: Describe the functional and technical requirements of this feature.
    validations:
      required: true

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Code implemented
        - label: Unit tests passed
        - label: Documentation updated

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional information or considerations.
    validations:
      required: false
