package com.neph.features.auth.util

import com.neph.ui.components.inputs.DropdownOption

val countryCodeOptions = listOf(
    DropdownOption(label = "🇦🇫 Afghanistan (+93)", value = "+93"),
    DropdownOption(label = "🇦🇱 Albania (+355)", value = "+355"),
    DropdownOption(label = "🇩🇿 Algeria (+213)", value = "+213"),
    DropdownOption(label = "🇦🇷 Argentina (+54)", value = "+54"),
    DropdownOption(label = "🇦🇲 Armenia (+374)", value = "+374"),
    DropdownOption(label = "🇦🇺 Australia (+61)", value = "+61"),
    DropdownOption(label = "🇦🇹 Austria (+43)", value = "+43"),
    DropdownOption(label = "🇦🇿 Azerbaijan (+994)", value = "+994"),
    DropdownOption(label = "🇧🇭 Bahrain (+973)", value = "+973"),
    DropdownOption(label = "🇧🇩 Bangladesh (+880)", value = "+880"),
    DropdownOption(label = "🇧🇾 Belarus (+375)", value = "+375"),
    DropdownOption(label = "🇧🇪 Belgium (+32)", value = "+32"),
    DropdownOption(label = "🇧🇷 Brazil (+55)", value = "+55"),
    DropdownOption(label = "🇧🇬 Bulgaria (+359)", value = "+359"),
    DropdownOption(label = "🇨🇦 Canada (+1)", value = "+1"),
    DropdownOption(label = "🇨🇱 Chile (+56)", value = "+56"),
    DropdownOption(label = "🇨🇳 China (+86)", value = "+86"),
    DropdownOption(label = "🇭🇷 Croatia (+385)", value = "+385"),
    DropdownOption(label = "🇨🇾 Cyprus (+357)", value = "+357"),
    DropdownOption(label = "🇨🇿 Czech Republic (+420)", value = "+420"),
    DropdownOption(label = "🇩🇰 Denmark (+45)", value = "+45"),
    DropdownOption(label = "🇪🇬 Egypt (+20)", value = "+20"),
    DropdownOption(label = "🇪🇪 Estonia (+372)", value = "+372"),
    DropdownOption(label = "🇫🇮 Finland (+358)", value = "+358"),
    DropdownOption(label = "🇫🇷 France (+33)", value = "+33"),
    DropdownOption(label = "🇬🇪 Georgia (+995)", value = "+995"),
    DropdownOption(label = "🇩🇪 Germany (+49)", value = "+49"),
    DropdownOption(label = "🇬🇷 Greece (+30)", value = "+30"),
    DropdownOption(label = "🇭🇺 Hungary (+36)", value = "+36"),
    DropdownOption(label = "🇮🇳 India (+91)", value = "+91"),
    DropdownOption(label = "🇮🇩 Indonesia (+62)", value = "+62"),
    DropdownOption(label = "🇮🇷 Iran (+98)", value = "+98"),
    DropdownOption(label = "🇮🇶 Iraq (+964)", value = "+964"),
    DropdownOption(label = "🇮🇪 Ireland (+353)", value = "+353"),
    DropdownOption(label = "🇮🇱 Israel (+972)", value = "+972"),
    DropdownOption(label = "🇮🇹 Italy (+39)", value = "+39"),
    DropdownOption(label = "🇯🇵 Japan (+81)", value = "+81"),
    DropdownOption(label = "🇯🇴 Jordan (+962)", value = "+962"),
    DropdownOption(label = "🇰🇿 Kazakhstan (+7)", value = "+7"),
    DropdownOption(label = "🇰🇼 Kuwait (+965)", value = "+965"),
    DropdownOption(label = "🇱🇧 Lebanon (+961)", value = "+961"),
    DropdownOption(label = "🇱🇹 Lithuania (+370)", value = "+370"),
    DropdownOption(label = "🇱🇺 Luxembourg (+352)", value = "+352"),
    DropdownOption(label = "🇲🇾 Malaysia (+60)", value = "+60"),
    DropdownOption(label = "🇲🇽 Mexico (+52)", value = "+52"),
    DropdownOption(label = "🇲🇦 Morocco (+212)", value = "+212"),
    DropdownOption(label = "🇳🇱 Netherlands (+31)", value = "+31"),
    DropdownOption(label = "🇳🇿 New Zealand (+64)", value = "+64"),
    DropdownOption(label = "🇳🇬 Nigeria (+234)", value = "+234"),
    DropdownOption(label = "🇳🇴 Norway (+47)", value = "+47"),
    DropdownOption(label = "🇵🇰 Pakistan (+92)", value = "+92"),
    DropdownOption(label = "🇵🇸 Palestine (+970)", value = "+970"),
    DropdownOption(label = "🇵🇭 Philippines (+63)", value = "+63"),
    DropdownOption(label = "🇵🇱 Poland (+48)", value = "+48"),
    DropdownOption(label = "🇵🇹 Portugal (+351)", value = "+351"),
    DropdownOption(label = "🇶🇦 Qatar (+974)", value = "+974"),
    DropdownOption(label = "🇷🇴 Romania (+40)", value = "+40"),
    DropdownOption(label = "🇷🇺 Russia (+7)", value = "+7"),
    DropdownOption(label = "🇸🇦 Saudi Arabia (+966)", value = "+966"),
    DropdownOption(label = "🇷🇸 Serbia (+381)", value = "+381"),
    DropdownOption(label = "🇸🇬 Singapore (+65)", value = "+65"),
    DropdownOption(label = "🇸🇰 Slovakia (+421)", value = "+421"),
    DropdownOption(label = "🇸🇮 Slovenia (+386)", value = "+386"),
    DropdownOption(label = "🇿🇦 South Africa (+27)", value = "+27"),
    DropdownOption(label = "🇰🇷 South Korea (+82)", value = "+82"),
    DropdownOption(label = "🇪🇸 Spain (+34)", value = "+34"),
    DropdownOption(label = "🇸🇪 Sweden (+46)", value = "+46"),
    DropdownOption(label = "🇨🇭 Switzerland (+41)", value = "+41"),
    DropdownOption(label = "🇸🇾 Syria (+963)", value = "+963"),
    DropdownOption(label = "🇹🇼 Taiwan (+886)", value = "+886"),
    DropdownOption(label = "🇹🇭 Thailand (+66)", value = "+66"),
    DropdownOption(label = "🇹🇳 Tunisia (+216)", value = "+216"),
    DropdownOption(label = "🇹🇷 Türkiye (+90)", value = "+90"),
    DropdownOption(label = "🇺🇦 Ukraine (+380)", value = "+380"),
    DropdownOption(label = "🇦🇪 United Arab Emirates (+971)", value = "+971"),
    DropdownOption(label = "🇬🇧 United Kingdom (+44)", value = "+44"),
    DropdownOption(label = "🇺🇸 United States (+1)", value = "+1"),
    DropdownOption(label = "🇺🇾 Uruguay (+598)", value = "+598"),
    DropdownOption(label = "🇺🇿 Uzbekistan (+998)", value = "+998"),
    DropdownOption(label = "🇻🇳 Vietnam (+84)", value = "+84"),
    DropdownOption(label = "🇾🇪 Yemen (+967)", value = "+967")
)